Repository Arquisoft/viade_en3a, pull requests merged in 2020-04, with the labels that each got.

#122 Add elevation to routes 107
  src/components/myElevationChart/MyElevationChart.js
  src/components/myMap/MyMap.js
  src/components/routeList/RouteList.js
  src/model/MyRoute.js
  src/model/RoutePoint.js
  src/model/RouteWaypoint.js
  src/pages/MapCreation.js
  src/tests/RouteManager.test.js
Labels: bugFix, enhancement

#127 Finished point 6 of the documentation
  src/docs/05_building_block_view.adoc
  src/docs/arc42-template.adoc
  src/docs/images/05_building_blocks-EN.png
  src/docs/images/08-Crosscutting-Concepts-Structure-EN.png
  src/docs/images/BusinessContext.png
  src/docs/images/viadeWhiteBoxLevel1.png
  src/docs/index.adoc
Labels: documentation, enhancement

#135 Fixing some codacy issues on readme file
  README.md
Labels: documentation, enhancement

#168 Better alerts in route creation
  package.json
  src/components/editableMap/EditableMap.js
  src/components/routeList/RouteList.js
  src/i18n.js
  src/pages/MapCreation.js
  src/tests/MapCreation.test.js
Labels: help wanted

#187 Feature waypoints
  src/assets/mapIcons/iconEdited-de.svg
  src/assets/mapIcons/iconEdited.svg
  src/assets/mapIcons/iconNormal-def.svg
  src/assets/mapIcons/iconNormal.svg
  src/assets/mapIcons/iconSelected-def.svg
  src/assets/mapIcons/iconSelected.svg
  src/components/editableMap/EditableMap.js
  src/components/myMap/MyMap.js
  src/components/pointInfo/PointInfo.js
  src/components/routeCreation/RouteCreationForm.js
  src/components/routeList/RouteCard.js
  src/model/MyRoute.js
  src/model/RoutePoint.js
  src/pages/InfoView.js
  src/pages/RouteCreation.js
  src/tests/PagesRender.test.js
  src/tests/RouteManager.test.js
Labels: enhancement

#210 Feature share groups
  src/components/podService/podStoreHandler.js
  src/components/routeCreation/SearchBar.js
  src/i18n.js
  src/pages/Groups.js
  src/pages/InfoView.js
  src/pages/RouteCreation.js
  src/pages/RouteList.js
  src/pages/RouteSharedList.js
  src/pages/ShareView.js
Labels: bugFix

#201 Documentation revisit
  src/docs/01_introduction_and_goals.adoc
  src/docs/03_system_scope_and_context.adoc
  src/docs/04_solution_strategy.adoc
  src/docs/05_building_block_view.adoc
  src/docs/06_runtime_view.adoc
  src/docs/07_deployment_view.adoc
  src/docs/09_design_decisions.adoc
  src/docs/10_quality_scenarios.adoc
  src/docs/images/10_qualityTree.png
  src/docs/images/BuildingBlock1.png
  src/docs/images/BusinessContext.png
  src/docs/images/DataClassDiagram.png
  src/docs/images/DeploymentView.png
  src/docs/images/NavMap.png
  src/docs/images/RuntimeViewRouteCreation.png
  src/docs/images/RuntimeViewRouteDetailed.png
  src/docs/images/TechnicalContext.png
  src/docs/images/viadeWhiteBoxLevel1.png
Labels: documentation

#227 fixed search bar
  src/components/routeCreation/SearchBar.js
Labels: PRIO: High, bug
