Repository Arquisoft/viade_en3a, pull requests merged in 2020-03, with the labels that each got.

#39 Feature route list gui
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/components/routeList/RouteCard.js
  src/components/routeList/RouteCard.test.js
  src/components/routeList/RouteCardLayout.css
  src/components/routeList/RouteCardStyle.css
  src/components/routeList/RouteList.js
  src/components/routeList/RouteList.test.js
  src/index.js
Labels: enhancement

#43 Fixed problems when comparing
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/components/myMap/MyMap.css
  src/components/myMap/MyMap.js
  src/components/myMap/MyMap.test.js
  src/components/myMap/Route.js
  src/docs/09_design_decisions.adoc
  src/setupTests.js
Labels: enhancement

#45 Feature route list gui
  .travis.yml
  package-lock.json
  package.json
  src/App.js
  src/components/routeList/RouteCard.js
  src/components/routeList/RouteCardLayout.css
  src/components/routeList/RouteCardStyle.css
  src/components/routeList/RouteList.js
  src/index.js
Labels: enhancement

#42 Feature nav bar
  package-lock.json
  src/App.js
  src/components/navBar/CustomNavBar.js
  src/index.js
Labels: enhancement

#47 Several modifications. Read commit description.
  src/App.js
  src/components/myMap/MyMap.js
  src/components/myMap/MyMap.test.js
  src/components/myMap/Route.js
  src/components/routeList/RouteCard.js
  src/components/routeList/RouteList.js
Labels: bugFix, enhancement

#66 Bug fix fix styles fix image display
  src/App.js
  src/assets/car_img1.jpeg
  src/assets/car_img2.jpg
  src/assets/github.png
  src/components/carousel/WelcomeCarousel.jsx
  src/components/editableMap/EditableMap.js
  src/components/myMap/MyMap.js
  src/components/navBar/navBar.jsx
  src/components/navBar/navBarNotAuthenticated.jsx
  src/components/podService/solid_file_client.js
  src/components/routeList/RouteCard.js
  src/components/routeList/RouteList.js
  src/pages/MapCreation.js
Labels: bugFix

#87 Fixed App.test and moved tests to a separate folder inside src
  src/tests/App.test.js
  src/tests/MapCreation.test.js
  src/tests/MyMap.test.js
  src/tests/RouteCard.test.js
  src/tests/RouteList.test.js
Labels: bugFix, testing

#99 Rewrote part 4 of the documentation
  src/docs/04_solution_strategy.adoc
  src/docs/12_glossary.adoc
Labels: documentation

#101 Modified InfoView interface
  src/App.js
  src/components/navBar/NavBarNotAuthenticated.css
  src/components/navBar/navBarNotAuthenticated.jsx
  src/css/App.css
  src/css/index.css
  src/css/infoView.css
  src/index.js
  src/pages/EditProfile.js
  src/pages/Friends.js
  src/pages/Home.js
  src/pages/InfoView.js
  src/pages/MapCreation.js
  src/pages/Profile.js
Labels: enhancement

#104 New route POD upload complete
  src/components/podService/podStoreHandler.js
  src/components/podService/solid_file_client.js
  src/model/MyRoute.js
  src/model/RouteManager.js
  src/model/RouteWaypoint.js
  src/pages/InfoView.js
  src/pages/MapCreation.js
  src/pages/Profile.js
  src/tests/InfoView.test.js
Labels: enhancement

#110 Fix route listing w no account
  src/App.js
  src/components/carousel/WelcomeCarousel.js
  src/components/myMap/MyMap.js
  src/components/navBar/navBar.js
  src/components/navBar/navBarNotAuthenticated.js
  src/components/pageNotFound/PageNotFound.js
  src/components/registerForm/RegisterForm.js
  src/css/MyMap.css
  src/model/RouteManager.js
  src/pages/Profile.js
  src/pages/SignUp.js
Labels: bugFix

#117 Async component created on route list
  src/components/routeList/RouteList.js
  src/model/RouteManager.js
Labels: bugFix

#118 Now the page reloads without crashing thanks to the state modification
  src/pages/InfoView.js
Labels: bugFix

#115 Input validation performed. Bug fixed
  package-lock.json
  src/pages/MapCreation.js
Labels: bugFix
